# Main entrypoint of the workflow.
# This file attempts to follow the good practice described at
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html.

rule all:
    input:
        expand("resources/luts/{file_name}.json", file_name=glob_wildcards(os.path.join("data", "{file_name}.xml.gz")).file_name)

rule gunzip:
    input:
        "resources/{file_name}.xml.gz"
    output:
        "resources/extracted/{file_name}.xml"
    run:
        shell("mkdir -p resources/extracted && gunzip -c {input} > {output}")

rule write_lut:
    input:
        "resources/extracted/{file_name}.xml"
    output:
        "resources/luts/{file_name}.json"

rule clean:
    threads: 1
    shell:
        "rm -rf data/extracted .cache/ .conda/ .snakemake/ logs/"